import {GoogleGenerativeAI} from "@google/generative-ai"

import NodeCache from "node-cache"
import dotenv from 'dotenv'

dotenv.config()

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY)

const aiCache= new NodeCache({stdTTL:3600}) //for 1 hr

const model = genAI.getGenerativeModel({
    model:process.env.GEMINI_MODEL,
    systemInstruction: `
You are an expert forex and currency market analyst.
Your job is to independently validate trading signals
generated by a quantitative algorithm.

You will be given:
- A quant-generated signal (BUY/SELL/NO_TRADE)
- Technical indicators (RSI, ADX, MACD, SuperTrend, BBWidth, HMA)
- Recent OHLC candle data
- Currency pair and timeframe

Your task:
1. Analyze the indicators and OHLC data independently
2. Give YOUR OWN signal — BUY, SELL, or NO_TRADE
3. State whether you AGREE or DISAGREE with the quant signal
4. Give 3-4 lines of clear reasoning — why you agree or disagree
5. Mention any macro risks or caution if indicators are mixed
6. If signals are unclear or contradictory — say NO_TRADE

Rules you must follow:
- Be concise — maximum 5 lines
- Never make absolute promises about market direction
- Always mention risk if present
- If quant says BUY but indicators look weak — say so clearly
- Respond in the same language the user asks in`

})


export const getAIValidation = async (symbol , interval , quantSignal , indicators, candles)=>{ //why only 5 candles

    const cacheKey= `ai_${symbol}_${interval}_${quantSignal.signal}`

    const cachedResponse = aiCache.get(cacheKey) //explain how cache code is written

    if(cachedResponse){
        console.log('RESP SERVED FROM CACHE')
        return{ success:true , data:cachedResponse , source: 'cache'}
    }
    try{
        const recentCandles = candles.slice(-20) //last 5 candles to keep token size less
        const prompt = `
        Analyze this currency pair and validate the quant signal:

        PAIR: ${symbol}
        TIMEFRAME: ${interval}

        QUANT MODEL SIGNAL: ${quantSignal.signal}
        QUANT SCORE: ${quantSignal.score}
        STOP LOSS: ${quantSignal.risk.stopLoss}
        TAKE PROFIT: ${quantSignal.risk.takeProfit}

        TECHNICAL INDICATORS:
        - RSI: ${indicators.rsi}
        - ADX: ${indicators.adx}
        - MACD Histogram: ${indicators.macdHist}
        - Bollinger Band Width: ${indicators.bbWidth}
        - SuperTrend Bias: ${indicators.supertrend} (1=bullish, -1=bearish)
        - HMA: ${indicators.hma}
        Note: Use your pretrained knowledge about 
        macro events, central bank policies, and 
        geopolitical factors for ${symbol} if relevant.
        Mention any such risks in your reasoning
        RECENT CANDLES (oldest to newest):
        ${recentCandles.map((c, i) =>
        `Candle ${i + 1}: O:${c.open} H:${c.high} L:${c.low} C:${c.close}`
        ).join('\n')}
        // template literal se dynamic prompt banaya
        // har value inject ki — AI ko poora context milega
        // candles ko map() se readable format mein convert kiya

        Give your independent signal and reasoning.
        `
        //why system instr and prompt diff
        const result = await model.generateContent(prompt)

        const responseText= result.response.text()

        const aiResponse = {
            aiSignal:extractSignal(responseText),
            reasoning:responseText,//COMPLETE TEXT
            agreesWithQuant:extractSignal(responseText)===quantSignal.signal,
            timestamp:Date.now()
        }
        aiCache.set(cacheKey,aiResponse)// saving resp in cache
        return{success:true, data:aiResponse,source:'api'}

    }
    catch(err){
        console.error('AI SERVICE ERROR:',err.message)
        return{success:false, error:'ai validation unavailable'}
    }   

}

const extractSignal= (text)=>{

    const upperText=text.toUpperCase()

    if (upperText.includes('NO_TRADE') || upperText.includes('NO TRADE')) return 'NO_TRADE'
    if (upperText.includes('BUY')) return 'BUY'
    if (upperText.includes('SELL')) return 'SELL'

    return 'NO_TRADE' //if extracted nothing give no-trade signal



}






